---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - nodejs

- name: Install Packages | npm
  npm:
    state: latest
    name: "{{ item }}"
    global: yes
  with_items: node_packages
