---
- name: Import Signing Key | ~chris-lea
  apt_key:
    state: present
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: '0xb9316a7bc7917b12'

- name: Import Repository | ~chris-lea/node.js
  apt_repository:
    state: present
    repo: 'deb http://ppa.launchpad.net/chris-lea/node.js/ubuntu trusty main'
  notify: Update Package Cache

- name: Trigger All Callbacks
  meta: flush_handlers

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - nodejs
